[package]
name = "rust_plotters_stock_market_ohlcv"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-edit = "0.12.3"
chrono = "0.4.38"
decimal = "2.1.0"
plotters = "0.3.6"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
rustfmt = "0.10.0"
